In [1]:
import psycopg2 

conn = psycopg2.connect(
    host="localhost",
    port="5432",
    user="postgres",
    password="csc101"
)


new_db_name = "mtn_nigeria"
conn.autocommit = True
cursor = conn.cursor()
cursor.execute(f"CREATE DATABASE {'mtn_nigeria'};")

cursor.close()


# Close the connection
conn.close()

In [3]:
conn = psycopg2.connect(
    host="localhost",
    port="5432",
    database="mtn_nigeria",
    user="postgres",
    password="csc101"
)


# Create a cursor object
cursor = conn.cursor()

# Define the CREATE TABLE statement
create_table_query = '''
    CREATE TABLE customer_info (
        name varchar,
        email varchar,
        state_of_residence  varchar ,
        mobile    varchar )
'''
cursor.execute(create_table_query)

conn.commit()

cursor.close()
conn.close()

In [11]:
import psycopg2

# Establish a connection to the PostgreSQL server
conn = psycopg2.connect(
    host="localhost",
    port="5432",
    database="mtn_nigeria",
    user="postgres",
    password="csc101"
)

# Create a cursor object
cursor = conn.cursor()

# Define the INSERT statement
insert_query = '''
    INSERT INTO customer_info (name, email, state_of_residence,mobile)
    VALUES (%s, %s, %s,%s)
'''

values = ('Favor Okpara-Ngbo', 'fokpara-ngbo@mtn.com', 'Lagos','08038212938')
values = ('Joshua Asekhauno','jasekhauno@mtn.com','Portharcourt','080374930210')
values =('Collins Odoh-Ifeanyi','codoh-ifeanyi@mtn.com','"Abuja','08067392029')
values = ('Chibundum Umeh','cumeh@mtn.com','Owerri','08034937123')
values = ('Clinto Okpara','cokpara@mtn.com','Kaduna','08068381138')

cursor.execute(insert_query, values)
conn.commit()
cursor.close()
conn.close()